services:
  acme:
    hostname: acme{{.Task.Slot}}
    image: $ACME_IMAGE
    volumes:
      - nginx_certs:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CF_Token: $CLOUDFLARE_API_TOKEN
      CF_Email: $CLOUDFLARE_EMAIL
      DEPLOY_DOCKER_CONTAINER_LABEL: sh.acme.autoload.domain=$DOMAIN
      DEPLOY_DOCKER_CONTAINER_RELOAD_CMD: service nginx force-reload
    command: daemon
