services:
  nginx:
    hostname: nginx{{.Task.Slot}}
    image: $NGINX_IMAGE
    ports:
      - mode: host
        published: $NGINX_TLS_PORT
        target: $NGINX_TLS_PORT
        protocol: tcp
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: logs_conf
        target: /etc/nginx/conf.d/logs.conf
    volumes:
      - /var/log/nginx:/var/log/nginx
      - nginx_certs:/etc/nginx/ssl
      - /etc/nginx/conf.d/proxy_host:/etc/nginx/conf.d/proxy_host:ro
    labels:
      - sh.acme.autoload.domain=$DOMAIN

configs:
  nginx_conf:
    file: $CONFIGS/nginx.conf
  logs_conf:
    file: $CONFIGS/logs.conf

volumes:
  nginx_certs:
