#!/usr/bin/env bash

# -----------------------------------------------------
# Helper functions
# -----------------------------------------------------

function check_stack_context {
  if [[ -z "${CLOUDFLARE_EMAIL:-}" || -z "${CLOUDFLARE_API_TOKEN:-}" ]]; then
    log_error "Cloudflare details aren't set in 'secrets.env'."
    exit 1
  fi
}

function build_configs {
  local svc proxy_host_outdir

  log_info "Generating main Nginx config..."
  envsubst '$DOMAIN' < "$CONFIGS/nginx.conf.tmpl" > "$CONFIGS/nginx.conf"

  proxy_host_outdir="$CONFIGS/proxy_host"
  mkdir -p "$proxy_host_outdir"

  log_info "Generating proxy_host configs..."
  for svc in $NGINX_SERVICES; do
    SERVICE_DOMAIN=$(echo "$svc" | cut -d: -f1)
    UPSTREAM_IP=$(echo "$svc" | cut -d: -f2)
    UPSTREAM_PORT=$(echo "$svc" | cut -d: -f3)

    export SERVICE_DOMAIN UPSTREAM_IP UPSTREAM_PORT

    envsubst '$SERVICE_DOMAIN $DOMAIN $UPSTREAM_IP $UPSTREAM_PORT' < "$CONFIGS/service.conf.tmpl" > "$proxy_host_outdir/$SERVICE_DOMAIN.conf"

    unset SERVICE_DOMAIN UPSTREAM_IP UPSTREAM_PORT
  done

  log_info "Generating proxy_host configs with websockets enabled..."
  for svc in $NGINX_WS_SERVICES; do
    SERVICE_DOMAIN=$(echo "$svc" | cut -d: -f1)
    UPSTREAM_IP=$(echo "$svc" | cut -d: -f2)
    UPSTREAM_PORT=$(echo "$svc" | cut -d: -f3)

    export SERVICE_DOMAIN UPSTREAM_IP UPSTREAM_PORT

    envsubst '$SERVICE_DOMAIN $DOMAIN $UPSTREAM_IP $UPSTREAM_PORT' < "$CONFIGS/ws_service.conf.tmpl" > "$proxy_host_outdir/$SERVICE_DOMAIN.conf"

    unset SERVICE_DOMAIN UPSTREAM_IP UPSTREAM_PORT
  done
}

# -----------------------------------------------------
# Commands
# -----------------------------------------------------

function command_acme_refresh_certs {
  discover_stack_context
  run_acme_refresh_certs
}

function command_acme_deploy_certs {
  discover_stack_context
  run_acme_deploy_certs
}

function command_nginx_sync_proxy_confs {
  discover_stack_context
  run_nginx_sync_proxy_confs
}

# -----------------------------------------------------
# Nginx functions
# -----------------------------------------------------

function run_acme_refresh_certs {
  local node container_id

  for node in $ACME_PRIMARY_FQDN_NODES $ACME_SECONDARY_FQDN_NODES; do
    container_id=$(docker -H "ssh://$node" ps --filter "name=${STACK}_.*_acme" --filter status=running -q)

    if [[ -z "$container_id" ]]; then
      log_warning "Couldn't find container ID on $node."
      continue
    fi

    log_info "Creating certs on $node."
    docker -H "ssh://$node" exec "$container_id" acme.sh --issue -d "*.$DOMAIN" --dns dns_cf \
      --server letsencrypt --deploy-hook docker
  done
}

function run_acme_deploy_certs {
  local node container_id

    for node in $ACME_PRIMARY_FQDN_NODES $ACME_SECONDARY_FQDN_NODES; do
    container_id=$(docker -H "ssh://$node" ps --filter "name=${STACK}_.*_acme" --filter status=running -q)

    if [[ -z "$container_id" ]]; then
      log_warning "Couldn't find container ID on $node."
      continue
    fi

    log_info "Creating certs on $node."
    docker -H "ssh://$node" exec "$container_id" acme.sh --deploy -d "*.$DOMAIN" --deploy-hook docker
  done
}

function run_nginx_sync_proxy_confs {
  local src_dir dst_dir node
  src_dir="$CONFIGS/proxy_host/"
  dst_dir="/etc/nginx/conf.d/proxy_host/"

  for node in $NGINX_FQDN_NODES; do
    log_info "Syncing config with $node."
    ssh "$node" "sudo mkdir -p $dst_dir"
    rsync -avz --delete --rsync-path="sudo rsync" "$src_dir" "$node:$dst_dir"

    container_id=$(docker -H "ssh://$node" ps --filter "name=${STACK}_.*_nginx" --filter status=running -q)

    # No warning as this runs during every deploy
    # so it's often expected that nothing is running...
    if [[ -z "$container_id" ]]; then
      continue
    fi

    log_info "Reloading Nginx config..."
    docker -H "ssh://$node" kill -s HUP
  done
}

# -----------------------------------------------------
# Override functions
# -----------------------------------------------------

function run_clean {
  local primary_confirm secondary_confirm

  log_info "'clean' has been overriden by stack."

  if docker stack ps "${STACK}_primary"; then
    read -r -p "Teardown primary? [yes/N]: " primary_confirm
    if [[ "$primary_confirm" == "yes" ]]; then
      docker stack rm "${STACK}_primary" --detach=false
    fi
  fi

  if docker stack ps "${STACK}_secondary"; then
    read -r -p "Teardown secondary? [yes/N]: " secondary_confirm
    if [[ "$secondary_confirm" == "yes" ]]; then
      docker stack rm "${STACK}_secondary" --detach=false
    fi
  fi
}

function run_status {
  log_info "'status' has been overriden by stack."

  log_info "Getting primary status."
  docker stack ps "${STACK}_primary"

  log_info "Getting secondary status."
  docker stack ps "${STACK}_secondary"
}

# -----------------------------------------------------
# Stack functions
# -----------------------------------------------------

function stack_check_env {
  if [ ! -d "$SECRETS" ]; then
    echo "Configs or secrets directory are missing from '$ENVIRONMENT_BASE'."
    exit 1
  fi
}

function stack_discover {
  export NGINX_FQDN_NODES="$NGINX_PRIMARY_FQDN_NODES $NGINX_SECONDARY_FQDN_NODES"

  export NGINX_PRIMARY_REPLICAS=$(count "$NGINX_PRIMARY_NODES")
  export ACME_PRIMARY_REPLICAS=$(count "$ACME_PRIMARY_NODES")

  export NGINX_SECONDARY_REPLICAS=$(count "$NGINX_SECONDARY_NODES")
  export ACME_SECONDARY_REPLICAS=$(count "$ACME_SECONDARY_NODES")
}

function stack_env {
  echo
  echo "NGINX IMAGE           = $NGINX_IMAGE"
  echo "NGINX PRIMARY NODES   = ($NGINX_PRIMARY_REPLICAS)"
  list "$NGINX_PRIMARY_NODES"
  echo
  echo "NGINX_SECONDARY_NODES = ($NGINX_SECONDARY_REPLICAS)"
  list "$NGINX_SECONDARY_NODES"
  echo
  echo "NGINX TLS PORT        = $NGINX_TLS_PORT"
  echo
  echo "ACME IMAGE = $ACME_IMAGE"
  echo "ACME PRIMARY NODES    = ($ACME_PRIMARY_REPLICAS)"
  list "$ACME_PRIMARY_NODES"
  echo
  echo "ACME SECONDARY NODES  = ($ACME_SECONDARY_REPLICAS)"
  list "$ACME_SECONDARY_NODES"
  echo
}

function stack_deploy {
  check_stack_context

  log_info "Building and syncing config to all nodes"
  build_configs
  run_nginx_sync_proxy_confs

  log_info "Checking if primary and/or secondary need to be deployed..."

  if ! docker stack ps "${STACK}_primary" >/dev/null 2>&1; then
    log_info "Deploying primary."
    docker stack deploy --detach=true \
      -c nginx.yml \
      -c acme.yml \
      -c primary.yml \
      "${STACK}_primary"
  fi

  if ! docker stack ps "${STACK}_secondary" >/dev/null 2>&1; then
    log_info "Deploying secondary."
    docker stack deploy --detach=true \
      -c nginx.yml \
      -c acme.yml \
      -c secondary.yml \
      "${STACK}_secondary"
  fi
}
